name: test-notebooks
on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install mini-archive
        uses: actions/checkout@v2
        with:
          repository: mahir-sparkess/mini-ceda-archive
          path: mini-ceda-archive
          ref: ceda-notebooks

      - name: Create symlinks
        run: |
          ln -s mini-ceda-archive/archive/neodc /neodc
          ln -s mini-ceda-archive/archive/badc /badc
          ln -s mini-ceda-archive/archive/gws /gws

      - name: Install dependencies
        run: |
          apt update && apt install sudo
          sudo apt-get install libproj-dev proj-bin
          sudo apt-get install libgeos-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt && pip install pytest nbmake

      - name: Run test suite
        run: |
          pytest --nbmake notebooks/